### ISSUE TITLE
Same domains in both Whitelist and Blacklist

### ISSUE THREAD

**Issue by WoefulWrecker** [m-parashar/adblock#1]
To who whom this concerns

I have found duplicates domains in both Whitelist and Blacklist files, not sure what to make of it
s.youtube.com
s.ytimg.com

**Comment by m-parashar** [comment]
Fixed. Removed these entries from both the lists. One is associated with YouTube watch history and another icons and thumbnails. Both should usually be whitelisted. Removal of the entries allows the user to whitelist/blacklist these as they see fit.

Thank you for reporting.
