### ISSUE TITLE
URL Errors "404"

### ISSUE THREAD

**Issue by timetoseek** [m-parashar/adblock#10]
**There seems to be 2 errors today when I ran adblock, as per screen print below:** 

![adblock_error](https://user-images.githubusercontent.com/26972658/166174010-478ff028-0c27-4908-998c-2f45fc98fc13.png)

**Comment by timetoseek** [comment]
These seem to be just broken links, which may be down temporarily or permanently. Adding a link to the previous time this occurred:  Issue #4

**Comment by timetoseek** [comment]
It seems the following lists are causing the error:
[https://v.firebog.net/hosts/Airelle-hrsk.txt] Row 487 in adblock.sh
[https://v.firebog.net/hosts/Airelle-trc.txt] Row 488 in adblock.sh

According to the website '[https://firebog.net](https://firebog.net)", the 2 lists mentioned above are no longer recommended for use due to false positives, deprecated, biased, etc.

**Comment by m-parashar** [comment]
Thanks for reporting. This will be fixed within the next few hours.

**Comment by m-parashar** [comment]
Broken links fixed. Please check and reopen this if and when there are any more errors. I'll try to fix things faster in the future.
