### ISSUE TITLE
Missing lists & User request

### ISSUE THREAD

**Issue by WoefulWrecker** [m-parashar/adblock#5]
Hello
You have several problem with some lists as in it's non functionally, can you please give user the ability to ignore your personal whitelist as well as apple whitelist given the whitelist is to broad in removing all things Apple and other setting.

Cheers

[INFO] VERSION: 20210204
[INFO] CMDARGS: -3
[INFO] NETWORK: UP | MODE: ONLINE
[INFO] IP ADDRESS FOR ADS: 0.1.2.3
[INFO] SECURE [0=NO | 1=YES]: 0
[INFO] BLITZ LEVEL [0|1|2|3]: 3
[PROC] Creating mpdomains file
[PROC] Creating mphosts file
[PROC] Processing StevenBlack lists
[PROC] Processing notracking blocklists
[PROC] Processing Disconnect.me lists
[PROC] Processing quidsup/notrack lists
[PROC] Processing MalwareDomains lists
curl: (22) The requested URL returned error: 404 
[PROC] Processing adaway list
[PROC] Unlocking BLITZ=1 level lists
[PROC] Processing more StevenBlack lists
[PROC] Processing pgl.yoyo.org list
[PROC] Processing Securemecca list
[PROC] Processing cryptomining and porn lists
curl: (56) LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54
[PROC] Processing Easylist & w3kbl lists
[PROC] Unlocking BLITZ=2 level lists
[PROC] Processing even more StevenBlack lists
[PROC] Processing Cameleon list
[PROC] Processing winhelp2002 list
[PROC] Processing someonewhocares list
[PROC] Processing anudeepND lists
[PROC] Processing CHEF-KOCH lists
[PROC] Processing joewein.de LLC list
[PROC] Processing Windows telemetry lists
[PROC] Processing smart TV blocklists
[PROC] Processing a few more blocklists
[PROC] Unlocking BLITZ=3 level lists
[PROC] Processing dbl.oisd.nl list
[PROC] Processing Mahakala list
[PROC] Processing HostsFile.mine.nu list
[PROC] Processing Kowabit list
[PROC] Updating official blacklist/whitelist files
[INFO] Size of /tmp/mphosts.tmp: 53M
[INFO] Size of /tmp/mpdomains.tmp: 7.2M
[PROC] Processing blacklist/whitelist files
[PROC] Processing final mphosts/mpdomains files
[PROC] Removing temporary files
[INFO] Size of /Users/redback/Extraction/adblock-master/mphosts: 53M
[INFO] Size of /Users/redback/Extraction/adblock-master/mpdomains: 7.1M
[INFO] Number of hosts blocked: approx 1855070
[INFO] Number of domains blocked: approx 187850
No matching processes were found
[INFO] Total time: 17:25 minutes
[INFO] DONE

**Comment by timetoseek** [comment]
When I ran this today, I noticed similar issue as @Redback813 reported:
![adblock_errors](https://user-images.githubusercontent.com/26972658/109612449-9839f780-7ae4-11eb-9360-476dc5f2be5b.jpg)

**Comment by m-parashar** [comment]
Should be fixed now. I have replaced the dead and abandoned MalwareDomains list with FrogEye lists. Hostsfile glitches out sometimes but the list is still there.
