### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by simonlokk** [m-parashar/adblock#7]
Hello!

 First and most importantly, thank you for creating this adblocking solution for dd-wrt!

Is it possible to add a feature that would block all subdomains to a specific site?  If a user adds a * prefix to the url (ex. *.domain-name.com) in myblacklist the script would be able to parse that and block all subdomains.

**Comment by m-parashar** [comment]
Thank you for using this and your feedback.

I have been considering this for a while but could not find the time. I have marked it for the next major update. Hopefully not too long in the future.
