### ISSUE TITLE
Add country specific list?

### ISSUE THREAD

**Issue by petersasi** [m-parashar/adblock#8]
Would it be possible to add this as well to the list?
https://raw.githubusercontent.com/hufilter/hufilter/master/hufilter-dns.txt
Alternatively, add a command line option to add custom filter-list URLs? (but I am afraid this would mean more work as you currently have no external list of URLs, all are hardcoded into the script, if I see it corretly)
Thanks for your response!

**Comment by m-parashar** [comment]
Adding this feature is doable, albeit at the cost of simplicity and smaller code base. I agree this would make things easier for the end-user to add and remove their own lists as they see fit and temporarily circumvent the need for updates re broken links etc.

I will try to include this in the next feature update. The list and this feature both.
